### ISSUE TITLE
Index page

### ISSUE THREAD

**Issue by RowinRuizendaal** [RowinRuizendaal/Bloom#3]
Making the index page (first screen), also setting up variables & project structure

**Comment by RowinRuizendaal** [comment]
- [x] Setting up SCSS Variables
- [x] Index page
- [x] Fixing linting issues

```SCSS
@import 'variables/colors';
@import 'variables/responsive';


* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}
```

Colors for now from the image:

```SCSS
// Primary colors
$yellow: #FEE89E;
$orange: #F07904;
$gray: #726d61;
$black: #151515;
$white: #FFFF;


// Secundaire colors
$red: #FEB4B0;
$green: #BAF0C5;
$blue: #C2EAFB;
$purple: #DAD0FB;

```
```SCSS
         h1 {
             color: $orange;
}
```
Also added the responsiveness in SCSS based on variables 👍🏻 

```SCSS
 .index__page {
     height: 100vh;
     display: flex;
     justify-content: center;
     align-items: center;
     flex-direction: column;
     background-image: url('../assets/svg/achtergrond.svg');
     background-position: center;
     background-size: cover 100% 100%;
     background-repeat: no-repeat;
     @include q-lg-min {
         background-size: cover;
     }

```

Include will tell in responsive.scss what breakpoint it has:

```SCSS
   $screen-xs: 320px; 
   $screen-sm: 576px;
   $screen-md: 768px;
   $screen-lg: 992px;
   $screen-xl: 1200px;
   $screen-xxl: 1300px;

   /* ==========================================================================
   Media Queries
   ========================================================================== */
   $screen-xs-min: ($screen-xs);
   $screen-sm-min: ($screen-sm);
   $screen-md-min: ($screen-md);
   $screen-lg-min: ($screen-lg);
   $screen-xl-min: ($screen-xl);
   $screen-xxl-min: ($screen-xxl);
   
   
@mixin q-xs-min {
    @media (max-width: $screen-xs-min) { 
        @content; 
    }
}
  
@mixin q-sm-min {
    @media (min-width: $screen-sm-min) { 
        @content; 
    }
}
  
@mixin q-md-min {
    @media (min-width: $screen-md-min) { 
        @content;
    }
}

@mixin q-lg-min {
    @media (min-width: $screen-lg-min) { 
        @content; 
    }
}

@mixin q-xl-min {
    @media (min-width: $screen-xl-min) { 
        @content; 
    }
}

@mixin q-xxl-min {
    @media (min-width: $screen-xxl-min) { 
        @content; 
    }
}
```
